In [1]:
import pandas as pd
import numpy as np
import config

import sqlalchemy
from sqlalchemy import create_engine

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier

from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

pd.options.mode.chained_assignment = None

In [2]:
engine = create_engine(f'postgresql://postgres:{config.password}@localhost:5432/crime_db')

In [3]:
crime_df = pd.read_sql("chicago", con=engine)
crime_df.head()

index        ID                Date       Primary_Type  \
0      0  11824091 2019-09-10 23:55:00  WEAPONS VIOLATION   
1      1  11824149 2019-09-10 23:50:00      OTHER OFFENSE   
2      2  11824121 2019-09-10 23:50:00            BATTERY   
3      3  11824152 2019-09-10 23:47:00    CRIMINAL DAMAGE   
4      5  11824113 2019-09-10 23:42:00            ASSAULT   

                 Description     Location_Description  Arrest District  Year  \
0       UNLAWFUL USE HANDGUN  RESIDENCE PORCH/HALLWAY   False      007  2019   
1  VEHICLE TITLE/REG OFFENSE                   STREET    True      006  2019   
2    DOMESTIC BATTERY SIMPLE                APARTMENT    True      015  2019   
3                TO PROPERTY                RESIDENCE   False      006  2019   
4                     SIMPLE                 SIDEWALK   False      015  2019   

    Latitude  Longitude Historical_Wards Zip_Codes Police_Districts  
0  41.775402 -87.653178               17     21559               17  
1  41.750582 -87.647984               17     21554               20  
2  41.880829 -87.752634               11     22216               25  
3  41.751657 -87.650131               17     21554               20  
4  41.899880 -87.748366                4      4299               25

In [4]:
crime_types = ['THEFT', 'BATTERY', 'CRIMINAL DAMAGE', 'NARCOTICS', 'ASSAULT', 
    'MOTOR VEHICLE THEFT', 'ROBBERY', 'WEAPONS VIOLATION', 'HOMICIDE', 'ARSON']

filtered_crime_df = crime_df[crime_df.Primary_Type.isin(crime_types)]
filtered_crime_df.head()

index        ID                Date       Primary_Type  \
0      0  11824091 2019-09-10 23:55:00  WEAPONS VIOLATION   
2      2  11824121 2019-09-10 23:50:00            BATTERY   
3      3  11824152 2019-09-10 23:47:00    CRIMINAL DAMAGE   
4      5  11824113 2019-09-10 23:42:00            ASSAULT   
7      8  11824122 2019-09-10 23:33:00            BATTERY   

               Description     Location_Description  Arrest District  Year  \
0     UNLAWFUL USE HANDGUN  RESIDENCE PORCH/HALLWAY   False      007  2019   
2  DOMESTIC BATTERY SIMPLE                APARTMENT    True      015  2019   
3              TO PROPERTY                RESIDENCE   False      006  2019   
4                   SIMPLE                 SIDEWALK   False      015  2019   
7  DOMESTIC BATTERY SIMPLE                    ALLEY    True      025  2019   

    Latitude  Longitude Historical_Wards Zip_Codes Police_Districts  
0  41.775402 -87.653178               17     21559               17  
2  41.880829 -87.752634               11     22216               25  
3  41.751657 -87.650131               17     21554               20  
4  41.899880 -87.748366                4      4299               25  
7  41.919319 -87.758462                4     22615                6

In [5]:
filtered_crime_df['Hour'] = filtered_crime_df['Date'].dt.hour
filtered_crime_df['Month'] = filtered_crime_df['Date'].dt.month
filtered_crime_df['Day'] = filtered_crime_df['Date'].dt.day
filtered_crime_df['Day_of_Week'] = filtered_crime_df['Date'].dt.weekday_name
filtered_crime_df['Day_of_Year'] = filtered_crime_df['Date'].dt.dayofyear

filtered_crime_df.head()

index        ID                Date       Primary_Type  \
0      0  11824091 2019-09-10 23:55:00  WEAPONS VIOLATION   
2      2  11824121 2019-09-10 23:50:00            BATTERY   
3      3  11824152 2019-09-10 23:47:00    CRIMINAL DAMAGE   
4      5  11824113 2019-09-10 23:42:00            ASSAULT   
7      8  11824122 2019-09-10 23:33:00            BATTERY   

               Description     Location_Description  Arrest District  Year  \
0     UNLAWFUL USE HANDGUN  RESIDENCE PORCH/HALLWAY   False      007  2019   
2  DOMESTIC BATTERY SIMPLE                APARTMENT    True      015  2019   
3              TO PROPERTY                RESIDENCE   False      006  2019   
4                   SIMPLE                 SIDEWALK   False      015  2019   
7  DOMESTIC BATTERY SIMPLE                    ALLEY    True      025  2019   

    Latitude  Longitude Historical_Wards Zip_Codes Police_Districts  Hour  \
0  41.775402 -87.653178               17     21559               17    23   
2  41.880829 -87.752634               11     22216               25    23   
3  41.751657 -87.650131               17     21554               20    23   
4  41.899880 -87.748366                4      4299               25    23   
7  41.919319 -87.758462                4     22615                6    23   

   Month  Day Day_of_Week  Day_of_Year  
0      9   10     Tuesday          253  
2      9   10     Tuesday          253  
3      9   10     Tuesday          253  
4      9   10     Tuesday          253  
7      9   10     Tuesday          253

In [6]:
# inflation_df = pd.read_csv("assets/data/Consumer_Price_Index_All_Urban_Consumers.csv")
# inflation_df.head()

# unemployment_df = pd.read_csv("assets/data/Illinois_Unemployment_Rate_2009-2019.csv")
# unemployment_df.head()

In [7]:
# merged_df = pd.merge(filtered_crime_df, inflation_df, on=(['Year', 'Month']), how='inner').fillna('Unknown')
# second_merged_df = pd.merge(merged_df, unemployment_df, on=(['Year', 'Month']), how='inner').fillna('Unknown')
# second_merged_df.head()

In [8]:
# bins = [0, 6, 12, 18, 23]
# labels = ['Night','Morning','Afternoon','Evening']
# model_df['Hour_Binned'] = pd.cut(model_df['Hour'], bins=bins, labels=labels)

group_names = ['Night','Morning','Afternoon','Evening']
filtered_crime_df["Hour_Bins"] = pd.cut(filtered_crime_df.Hour, bins=4, labels=group_names)

In [9]:
filtered_crime_df.round({'Latitude': 2, 'Longitude': 2})

index        ID                Date         Primary_Type  \
0              0  11824091 2019-09-10 23:55:00    WEAPONS VIOLATION   
2              2  11824121 2019-09-10 23:50:00              BATTERY   
3              3  11824152 2019-09-10 23:47:00      CRIMINAL DAMAGE   
4              5  11824113 2019-09-10 23:42:00              ASSAULT   
7              8  11824122 2019-09-10 23:33:00              BATTERY   
8              9  11824162 2019-09-10 23:30:00              ROBBERY   
9             10  11824148 2019-09-10 23:30:00              BATTERY   
10            11  11824756 2019-09-10 23:30:00      CRIMINAL DAMAGE   
11            12  11824127 2019-09-10 23:30:00                THEFT   
14            15  11824100 2019-09-10 23:10:00            NARCOTICS   
15            16  11824130 2019-09-10 23:01:00    WEAPONS VIOLATION   
16            17  11824489 2019-09-10 23:00:00                THEFT   
17            18  11824283 2019-09-10 23:00:00                THEFT   
18            19  11824165 2019-09-10 23:00:00              ROBBERY   
19            20  11824459 2019-09-10 23:00:00              BATTERY   
20            22  11824108 2019-09-10 23:00:00              BATTERY   
21            23  11825424 2019-09-10 23:00:00  MOTOR VEHICLE THEFT   
22            24  11824285 2019-09-10 23:00:00      CRIMINAL DAMAGE   
23            26  11824348 2019-09-10 23:00:00                THEFT   
26            29  11824083 2019-09-10 22:53:00              BATTERY   
27            30  11824097 2019-09-10 22:50:00              ASSAULT   
28            31  11824111 2019-09-10 22:48:00      CRIMINAL DAMAGE   
29            32  11824188 2019-09-10 22:45:00              BATTERY   
32            35  11824239 2019-09-10 22:34:00                THEFT   
33            36  11824190 2019-09-10 22:30:00              BATTERY   
34            37  11824396 2019-09-10 22:30:00                THEFT   
35            38  11824890 2019-09-10 22:30:00              BATTERY   
36            39  11824786 2019-09-10 22:30:00                THEFT   
37            40  11824261 2019-09-10 22:30:00      CRIMINAL DAMAGE   
38            41  11824237 2019-09-10 22:29:00              BATTERY   
...          ...       ...                 ...                  ...   
2868887  2889489   7808351 2010-01-01 00:01:00                THEFT   
2868888  2889490   7297693 2010-01-01 00:01:00      CRIMINAL DAMAGE   
2868896  2889498   7298927 2010-01-01 00:01:00                THEFT   
2868897  2889499   8058015 2010-01-01 00:01:00                THEFT   
2868900  2889502   7366197 2010-01-01 00:01:00                THEFT   
2868907  2889509   7940114 2010-01-01 00:01:00                THEFT   
2868910  2889512   7359063 2010-01-01 00:01:00                THEFT   
2868911  2889513   7917267 2010-01-01 00:01:00                THEFT   
2868912  2889514   7492284 2010-01-01 00:01:00                THEFT   
2868913  2889515   7968360 2010-01-01 00:01:00                THEFT   
2868914  2889516   7297505 2010-01-01 00:01:00      CRIMINAL DAMAGE   
2868919  2889521   8744058 2010-01-01 00:01:00                THEFT   
2868920  2889522   9281626 2010-01-01 00:01:00                THEFT   
2868928  2889533   8809628 2010-01-01 00:01:00                THEFT   
2868929  2889534   9220064 2010-01-01 00:01:00                THEFT   
2868930  2889536   9048498 2010-01-01 00:01:00                THEFT   
2868931  2889537   9069377 2010-01-01 00:01:00                THEFT   
2868932  2889539   8503993 2010-01-01 00:01:00                THEFT   
2868933  2889540   9491668 2010-01-01 00:01:00                THEFT   
2868936  2889545   8869943 2010-01-01 00:01:00                THEFT   
2868937  2889546   9314103 2010-01-01 00:01:00                THEFT   
2868941  2889552   9503921 2010-01-01 00:01:00                THEFT   
2868943  2889554   8747529 2010-01-01 00:01:00                THEFT   
2868947  2889560   8503577 2010-01-01 00:01:00                THEFT   
2868949  2889563   8360688 2010-01-

In [10]:
#List of relevant columns for model
col_list = [ 'Year','Month','Day_of_Week','Hour_Bins','Primary_Type','Latitude',
            'Longitude','Location_Description', 'Arrest','Zip_Codes', 'Police_Districts']

#Dataframe created from list of relevant columns
model_df = filtered_crime_df[col_list]
model_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2199080 entries, 0 to 2868956
Data columns (total 11 columns):
Year                    int64
Month                   int64
Day_of_Week             object
Hour_Bins               category
Primary_Type            object
Latitude                float64
Longitude               float64
Location_Description    object
Arrest                  bool
Zip_Codes               object
Police_Districts        object
dtypes: bool(1), category(1), float64(2), int64(2), object(5)
memory usage: 172.0+ MB


In [11]:
null_columns = model_df.columns[model_df.isnull().any()]
model_df[null_columns].isnull().sum()

Location_Description    707
dtype: int64

In [12]:
model_df["Location_Description"].fillna("Unknown", inplace = True)

In [13]:
# model_df = model_df[:25000]

In [14]:
X = model_df.drop(['Primary_Type'], axis=1)
y = model_df['Primary_Type']

print(X.shape)
print(y.shape)

(2199080, 10)
(2199080,)


In [15]:
#encode string variables for input into the classification model:
encoded_X = pd.get_dummies(X, columns=['Location_Description', 'Zip_Codes', 'Hour_Bins', 'Day_of_Week','Police_Districts'])
print(encoded_X.shape)
# encoded_y = pd.get_dummies(y, columns=['Primary_Type'])

(2199080, 286)


In [16]:
# create scaler
scaler = MinMaxScaler()
normalized_X = scaler.fit_transform(encoded_X)

/anaconda2/envs/LearnPython3/lib/python3.7/site-packages/sklearn/preprocessing/data.py:334: DataConversionWarning: Data with input dtype bool, uint8, int64, float64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)


In [17]:
X_train, X_test, y_train, y_test = train_test_split(normalized_X, y, test_size = 0.25, random_state = 21)

In [18]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(X_train, y_train)
print(f"Training Data Score: {classifier.score(X_train, y_train)}")
print(f"Testing Data Score: {classifier.score(X_test, y_test)}")

/anaconda2/envs/LearnPython3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/anaconda2/envs/LearnPython3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


Training Data Score: 0.49186387034578094
Testing Data Score: 0.49194754169925603


In [19]:
predictions = classifier.predict(X_test)
pd.DataFrame({"Prediction": predictions, "Actual": y_test})

Prediction               Actual
620197               BATTERY              ASSAULT
177652             NARCOTICS    WEAPONS VIOLATION
936012               BATTERY              BATTERY
2341060      CRIMINAL DAMAGE      CRIMINAL DAMAGE
1319042                THEFT              ROBBERY
2220580                THEFT              ROBBERY
1351423      CRIMINAL DAMAGE                THEFT
1364771              BATTERY              BATTERY
1913384                THEFT                THEFT
2654588              BATTERY      CRIMINAL DAMAGE
2239493                THEFT  MOTOR VEHICLE THEFT
2497480              BATTERY                THEFT
557960               BATTERY              BATTERY
79765                BATTERY                THEFT
2080161              BATTERY              BATTERY
892906                 THEFT      CRIMINAL DAMAGE
1990349                THEFT      CRIMINAL DAMAGE
2562833                THEFT                THEFT
196863                 THEFT                THEFT
87736                BATTERY              BATTERY
353470               BATTERY      CRIMINAL DAMAGE
1911835              BATTERY              BATTERY
1919364  MOTOR VEHICLE THEFT  MOTOR VEHICLE THEFT
566744                 THEFT      CRIMINAL DAMAGE
892129                 THEFT  MOTOR VEHICLE THEFT
722586                 THEFT  MOTOR VEHICLE THEFT
880309                 THEFT              ROBBERY
304527               BATTERY              BATTERY
1008884            NARCOTICS    WEAPONS VIOLATION
1058394                THEFT      CRIMINAL DAMAGE
...                      ...                  ...
2260055              BATTERY              BATTERY
1976739            NARCOTICS              ROBBERY
954091             NARCOTICS              ROBBERY
633852             NARCOTICS    WEAPONS VIOLATION
1716064                THEFT              ASSAULT
1098803              BATTERY              ROBBERY
1887924                THEFT  MOTOR VEHICLE THEFT
2281063              BATTERY              BATTERY
1774012              BATTERY      CRIMINAL DAMAGE
1762884                THEFT              BATTERY
816416                 THEFT              ROBBERY
834246               BATTERY              ASSAULT
2474658  MOTOR VEHICLE THEFT      CRIMINAL DAMAGE
421569                 THEFT                THEFT
649208                 THEFT                THEFT
363209               BATTERY                THEFT
1058368                THEFT                THEFT
441942       CRIMINAL DAMAGE                THEFT
1162484              BATTERY                THEFT
1377170                THEFT                THEFT
562205               BATTERY              BATTERY
441010             NARCOTICS            NARCOTICS
1555457      CRIMINAL DAMAGE      CRIMINAL DAMAGE
162880       CRIMINAL DAMAGE      CRIMINAL DAMAGE
2580037            NARCOTICS              ASSAULT
2708600                THEFT                THEFT
2636059              BATTERY                THEFT
2718884                THEFT      CRIMINAL DAMAGE
2622011                THEFT                THEFT
2094353            NARCOTICS            NARCOTICS

[549770 rows x 2 columns]

In [21]:
classifier = RandomForestClassifier(n_estimators = 100, criterion = 'entropy', random_state = 42)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test,y_pred))

0.4752096331193044
[[    34     22    313    232      1     23     36     15    372      5]
 [    17   3119  18702   4200     15   1260   4309   1312  13337    255]
 [    39   6049  68538  11473     34   2766   8990   4233  27311    574]
 [    31   2396  20694  17784     32   4868   1888   1154  27947    195]
 [     2     22    272    140    257     96    195     31    217     18]
 [     8    715   3210   6009     23   6521   1467    670  12874     89]
 [     6    816   5694    313     13    184  53333    135    866    828]
 [     7   1024   9519   2335     16   1313   1381   3960   8623     73]
 [    48   3876  24754  14981     20   6330   2083   2706 107137    153]
 [     1    312   2643    376      8    145   5018    148    608    573]]
                     precision    recall  f1-score   support

              ARSON       0.18      0.03      0.05      1053
            ASSAULT       0.17      0.07      0.10     46526
            BATTERY       0.44      0.53      0.48    130007
    C

In [22]:
grad_class = GradientBoostingClassifier(learning_rate=0.1,n_estimators = 10, random_state = 42)
grad_class.fit(X_train, y_train)
y_pred_grad = grad_class.predict(X_test)

print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred)) 
print(classification_report(y_test,y_pred_grad)) 

0.4752096331193044
[[    34     22    313    232      1     23     36     15    372      5]
 [    17   3119  18702   4200     15   1260   4309   1312  13337    255]
 [    39   6049  68538  11473     34   2766   8990   4233  27311    574]
 [    31   2396  20694  17784     32   4868   1888   1154  27947    195]
 [     2     22    272    140    257     96    195     31    217     18]
 [     8    715   3210   6009     23   6521   1467    670  12874     89]
 [     6    816   5694    313     13    184  53333    135    866    828]
 [     7   1024   9519   2335     16   1313   1381   3960   8623     73]
 [    48   3876  24754  14981     20   6330   2083   2706 107137    153]
 [     1    312   2643    376      8    145   5018    148    608    573]]


/anaconda2/envs/LearnPython3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


                     precision    recall  f1-score   support

              ARSON       0.00      0.00      0.00      1053
            ASSAULT       0.00      0.00      0.00     46526
            BATTERY       0.46      0.53      0.49    130007
    CRIMINAL DAMAGE       0.58      0.04      0.08     76989
           HOMICIDE       1.00      0.22      0.37      1250
MOTOR VEHICLE THEFT       0.00      0.00      0.00     31586
          NARCOTICS       0.57      0.93      0.71     62188
            ROBBERY       0.40      0.01      0.02     28251
              THEFT       0.44      0.80      0.57    162088
  WEAPONS VIOLATION       0.00      0.00      0.00      9832

          micro avg       0.47      0.47      0.47    549770
          macro avg       0.35      0.25      0.22    549770
       weighted avg       0.41      0.47      0.38    549770



In [ ]:
from tpot import TPOTClassifier
pipeline_optimizer = TPOTClassifier()

pipeline_optimizer = TPOTClassifier(generations=5, population_size=20, cv=5,
                                    random_state=42, verbosity=2, warm_start=True)

pipeline_optimizer.fit(X_train, y_train)

print(pipeline_optimizer.score(X_test, y_test))

In [ ]:
pipeline_optimizer.export('tpot_exported_pipeline.py')